test_data = [
    """
    This is the first sentence. 
    Good evening my love! 
    How difficult it was to leave my cute and cuddly Pepe Queen this morning, wanting to crawl under the covers and KISS KISS her.
    Her body still remains in my bed as she has shed her outfit in the same way that a snake sheds its skin. 
    Today was an incredibly productive day of meetings, to the point where I have almost lost my voice.
    Out of the conversations, one may even already lead to an investment I may get personal access to following the new strategy discussed yesterday night. 
    Today has also marked a significantly positive turn in the market, with Bitcoin up an unbelievable 10% in 24 hours. 
    I am sitting patiently upon my tiny digital empire, watching humbly as my land blossoms and the world is quiet to my knowledge and secrets. 
    I will update you more tomorrow - goodnight my dear 😴💓 Happy Saturday my beautiful darling! 
    🥹 Another crisp and sunny winter day to spend indoors together in front of some big screens and each other. 
    There's not much to share on my cousin's front, other than they had been together since 2018 which is likely around the last time I saw him, and she is from a tiny town in the middle of nowhere over by him in Michigan. 
    I did bring up one topic that made her have an outsized reaction and roll her eyes which was whether he wanted to move from Michigan to somewhere else 🤭 I will kiss kiss 😘 and banana banana 🍌 you soon!
    I miss you!
    Happy Friyay Love! ❤️ Enjoy your relaxing day at home filled with lots of destressing and watching of friends 🤗 
    It would be wonderful to try out the special egg yolk one because I am addicted to being the super special person in your life 🤭 
    You also have a card from valentines that I hid in our shared email inbox for you to open wuuuuu 😖 See you tomorrow my Beebee and be prepared for lots more feelings of being loved! 😘🐝",
    I've spotted our first day with a temperature in the 60s coming Wednesday 😲 I won't speak too soon but Mr. Snow may be gone for the rest of 2024 😎 How nice the dream of living in Miami feels for half of the year up in the north! We can fix up your helium mobile this weekend and get you back in mapping action earning that stable income source for the family 🤭 I'll be meeting with my cousin in the afternoon for lunch tomorrow rather than what I originally thought would be dinner. And I also will get a chance to meet his fiance too so I suppose I will have to be on my best behavior and see if there is tea to extract 😮‍💨 If you would like to stay over tomorrow after your class since I'll be gone next weekend, that is an option! But up to you my love and what you feel is most convenient 😚 Wishing you sweet dreams and warm wax baths for those soft hands and feet hehe. Goodnight Love! ❤️💤
    To quickly catch you up on the tea (or lack thereof) 🫖, I have not spoken to Tanner or many others outside of New York in some time. My strategy is one of humble silence, and until I have fully made back the money lost in 2021 & 2022 I have nothing to brag about 🫣 Afterwards, there is no point in telling others that have not been part of the journey as they will only seek to figure out what benefit they can take from your success. Since they have not taken the time to give back the efforts that I have put into that friendship, instead I will use them as data points for my investments 🧐 I am planning on keeping track of a little notepad, where I note the date of when someone reaches back out and if they mention crypto. When I get to a point where the rate increases for a period of ~3-6 months, then I know it will be my time to sell 🤭 As for Ethan, he's doing well and told me of his team dynamics that he is struggling to fit into, because the two other members are Chinese and they speak in Chinese back and forth 😥 He is getting the poor reverse foreigner experience competing with the top financial and math talents hehe. Everyone else in general is not experiencing too many major difficulties, just the little hardships with work & the economy that we all feel!
    """
]